name: uranus
description: An anime radio app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  audioplayers: ^0.20.1
  web_socket_channel: ^2.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  palette_generator: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1


flutter:

  uses-material-design: true

  assets:
    - assets/


